// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMX7f5wp4GycWTSANpL8T6YQE2V5TX74Q',
    appId: '1:642133256035:web:896708af8cb89d0c865556',
    messagingSenderId: '642133256035',
    projectId: 'test-login6-91cb0',
    authDomain: 'test-login6-91cb0.firebaseapp.com',
    storageBucket: 'test-login6-91cb0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS7wj1n0L-AUYXIfQLSmriWzc2Q5CsM1s',
    appId: '1:642133256035:android:477a70a328e2e765865556',
    messagingSenderId: '642133256035',
    projectId: 'test-login6-91cb0',
    storageBucket: 'test-login6-91cb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuKBWXCrz_2iVU_TE3B_EBB4aSqjelsw0',
    appId: '1:642133256035:ios:8b874d218a6642d2865556',
    messagingSenderId: '642133256035',
    projectId: 'test-login6-91cb0',
    storageBucket: 'test-login6-91cb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuKBWXCrz_2iVU_TE3B_EBB4aSqjelsw0',
    appId: '1:642133256035:ios:8b874d218a6642d2865556',
    messagingSenderId: '642133256035',
    projectId: 'test-login6-91cb0',
    storageBucket: 'test-login6-91cb0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMX7f5wp4GycWTSANpL8T6YQE2V5TX74Q',
    appId: '1:642133256035:web:b81907619bc14316865556',
    messagingSenderId: '642133256035',
    projectId: 'test-login6-91cb0',
    authDomain: 'test-login6-91cb0.firebaseapp.com',
    storageBucket: 'test-login6-91cb0.firebasestorage.app',
  );

}